Fix ChakraProviderProps error
The error `src/pages/Login.tsx(21,6): error TS2741: Property 'value' is missing in type '{ children: Element; }' but required in type 'ChakraProviderProps'` is caused by incorrect usage of the ChakraProvider component. The code will be updated to correctly use the ChakraProvider.